import { useState } from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { api } from '../../lib/api';

export function QuizStartScreen({ navigation }: { navigation: { goBack: () => void; navigate: ((route: 'QuizQuestion', params: { sessionId: string }) => void) & ((route: 'Premium') => void) } }) {
  const [count, setCount] = useState<5 | 10>(5); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [needsPremium, setNeedsPremium] = useState(false);
  // 403: the requested level is above the user's plan (entitlement MaxLevel) — show the server message and the paywall CTA.
  const start = async () => { if (loading) return; setLoading(true); setError(''); setNeedsPremium(false); try { const session = await api.createQuiz({ questionCount: count }); navigation.navigate('QuizQuestion', { sessionId: session.id }); } catch (e) { const apiError = e as { status?: number; message?: string }; if (apiError.status === 403) { setNeedsPremium(true); setError(apiError.message || 'Bu seviye planına dahil değil. Premium ile tüm seviyeleri açabilirsin.'); } else setError(apiError.status === 0 ? 'Bağlantı yok. İnternetini kontrol edip tekrar dene.' : (apiError.status ?? 0) >= 500 ? 'Sunucu hatası, tekrar dene.' : apiError.message ?? 'Quiz başlatılamadı.'); } finally { setLoading(false); } };
  return <ScrollView className="flex-1 bg-background px-6 pt-14" contentContainerStyle={{ paddingBottom: 48 }}><Pressable accessibilityRole="button" accessibilityLabel="Geri dön" onPress={navigation.goBack}><Text className="font-semibold text-blue-700">‹ Geri</Text></Pressable><View className="mt-8 rounded-3xl bg-foreground p-6"><Text className="text-xs font-bold uppercase tracking-widest text-blue-200">KENDİNİ ÖLÇ</Text><Text className="mt-3 text-3xl font-bold text-white">Mini quiz</Text><Text className="mt-2 leading-5 text-white/65">Öğrendiğin kelimeleri dört seçenekli kısa bir testle pekiştir.</Text></View><Text className="mt-8 text-xs font-bold uppercase tracking-widest text-muted-foreground">Soru sayısı</Text><View className="mt-3 flex-row gap-3"><Pressable accessibilityRole="button" accessibilityState={{ selected: count === 5 }} onPress={() => setCount(5)} className={`flex-1 rounded-2xl border-2 p-5 ${count === 5 ? 'border-primary bg-primary-soft' : 'border-border bg-surface'}`}><Text className={`text-center text-lg font-bold ${count === 5 ? 'text-primary' : 'text-foreground'}`}>5 soru</Text><Text className="mt-1 text-center text-xs text-muted-foreground">Hızlı seans</Text></Pressable><Pressable accessibilityRole="button" accessibilityState={{ selected: count === 10 }} onPress={() => setCount(10)} className={`flex-1 rounded-2xl border-2 p-5 ${count === 10 ? 'border-primary bg-primary-soft' : 'border-border bg-surface'}`}><Text className={`text-center text-lg font-bold ${count === 10 ? 'text-primary' : 'text-foreground'}`}>10 soru</Text><Text className="mt-1 text-center text-xs text-muted-foreground">Derin tekrar</Text></Pressable></View>{error ? <View accessibilityRole="alert" className={`mt-5 rounded-2xl p-4 ${needsPremium ? 'bg-amber-50' : 'bg-red-50'}`}><Text className={needsPremium ? 'text-amber-800' : 'text-red-700'}>{error}</Text>{needsPremium ? <Pressable accessibilityRole="button" accessibilityLabel="Premium paketlerini gör" onPress={() => navigation.navigate('Premium')} className="mt-3 items-center rounded-2xl bg-amber-500 py-3"><Text className="font-bold text-white">Premium'a geç</Text></Pressable> : null}</View> : null}<Pressable accessibilityRole="button" accessibilityLabel="Quiz başlat" accessibilityState={{ disabled: loading, busy: loading }} disabled={loading} onPress={() => void start()} className="mt-8 items-center rounded-2xl bg-accent py-4"><Text className="font-bold text-white">{loading ? 'Hazırlanıyor…' : 'Teste başla'}</Text></Pressable></ScrollView>;
}
