import { useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { api } from '../../lib/api';

export function QuizStartScreen({ navigation }: { navigation: { goBack: () => void; navigate: (route: 'QuizQuestion', params: { sessionId: string }) => void } }) {
  const [count, setCount] = useState<5 | 10>(5); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const start = async () => { setLoading(true); setError(''); try { const session = await api.createQuiz({ questionCount: count }); navigation.navigate('QuizQuestion', { sessionId: session.id }); } catch (e) { setError((e as { message?: string }).message ?? 'Quiz başlatılamadı.'); } finally { setLoading(false); } };
  return <View className="flex-1 bg-background px-6 pt-16"><Pressable onPress={navigation.goBack}><Text className="font-semibold text-blue-700">‹ Geri</Text></Pressable><Text className="mt-8 text-3xl font-bold text-foreground">Quiz başlat</Text><Text className="mt-2 text-muted-foreground">Her soruda doğru seçeneği işaretle.</Text><Text className="mt-10 text-sm font-semibold text-muted-foreground">SORU SAYISI</Text><View className="mt-3 flex-row gap-3"><Pressable onPress={() => setCount(5)} className={`flex-1 rounded-2xl p-5 ${count === 5 ? 'bg-blue-600' : 'bg-white'}`}><Text className={`text-center text-lg font-bold ${count === 5 ? 'text-white' : 'text-foreground'}`}>5 soru</Text></Pressable><Pressable onPress={() => setCount(10)} className={`flex-1 rounded-2xl p-5 ${count === 10 ? 'bg-blue-600' : 'bg-white'}`}><Text className={`text-center text-lg font-bold ${count === 10 ? 'text-white' : 'text-foreground'}`}>10 soru</Text></Pressable></View>{error ? <Text className="mt-5 text-red-700">{error}</Text> : null}<Pressable disabled={loading} onPress={() => void start()} className="mt-10 items-center rounded-2xl bg-amber-500 py-4"><Text className="font-bold text-white">{loading ? 'Hazırlanıyor…' : 'Teste başla'}</Text></Pressable></View>;
}
