import { useQuery } from '@tanstack/react-query';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { api } from '../../lib/api';
import { useAuthStore } from '../../store/auth-store';

export function HomeScreen({ navigation }: { navigation: { navigate: (route: 'Vocabulary' | 'Learn' | 'DailyMission' | 'SentenceChallenge' | 'WritingChallenge' | 'MatchingChallenge' | 'PracticeSession' | 'Leaderboard' | 'LearningPaths' | 'QuizStart' | 'Premium') => void } }) {
  const user = useAuthStore((state) => state.user);
  const signOut = useAuthStore((state) => state.signOut);
  const dashboard = useQuery({ queryKey: ['dashboard'], queryFn: api.dashboard });
  const entitlement = useQuery({ queryKey: ['entitlement'], queryFn: api.entitlement });
  const weeklyStats = useQuery({ queryKey: ['statistics', 'weekly'], queryFn: api.weeklyStats });
  const data = dashboard.data;
  const progress = data && data.dailyGoal > 0 ? Math.min(1, data.todayProgress / data.dailyGoal) : 0;
  const firstName = user?.displayName || user?.email?.split('@')[0] || 'Öğrenci';
  return <ScrollView className="flex-1 bg-background px-5 pt-14" contentContainerStyle={{ paddingBottom: 48 }}>
    <View className="flex-row items-center justify-between"><View className="flex-row items-center"><View className="h-12 w-12 items-center justify-center rounded-2xl bg-primary"><Text className="text-lg font-bold text-white">{firstName.slice(0, 1).toUpperCase()}</Text></View><View className="ml-3"><Text className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">Hoş geldin</Text><Text className="mt-1 text-xl font-bold text-foreground">{firstName}</Text></View></View><Pressable accessibilityRole="button" accessibilityLabel="Oturumu kapat" onPress={() => void signOut()} className="rounded-full bg-surface px-4 py-2"><Text className="text-sm font-semibold text-muted-foreground">Çıkış</Text></Pressable></View>
    {dashboard.isError ? <Text accessibilityRole="alert" className="mt-5 rounded-2xl bg-red-50 p-4 text-red-700">İstatistikler yüklenemedi.</Text> : null}
    <View className="mt-7 overflow-hidden rounded-3xl bg-foreground p-6"><View className="flex-row items-center justify-between"><Text className="text-xs font-bold uppercase tracking-widest text-blue-200">Bugünün ritmi</Text><Text className="rounded-full bg-white/10 px-3 py-1 text-xs font-semibold text-white">{data?.currentLevel ?? 'Seviye seçilmedi'}</Text></View><Text className="mt-4 text-4xl font-bold text-white">{data?.todayProgress ?? 0} <Text className="text-2xl text-white/50">/ {data?.dailyGoal ?? '—'}</Text></Text><Text className="mt-1 text-sm text-white/65">kelime hedefi tamamlandı</Text><View className="mt-5 h-2 overflow-hidden rounded-full bg-white/15"><View className="h-2 rounded-full bg-blue-400" style={{ width: `${progress * 100}%` }} /></View><Text className="mt-3 text-sm text-white/70">{Math.round(progress * 100)}% tamamlandı</Text></View>
    <View className="mt-4 flex-row gap-2"><View className="flex-1 rounded-2xl border border-border bg-surface p-4"><Text className="text-2xl font-bold text-foreground">{data?.dueReviewCount ?? 0}</Text><Text className="mt-1 text-xs font-medium text-muted-foreground">Bekleyen tekrar</Text></View><View className="flex-1 rounded-2xl border border-border bg-surface p-4"><Text className="text-2xl font-bold text-foreground">{data?.totalWordsLearned ?? 0}</Text><Text className="mt-1 text-xs font-medium text-muted-foreground">Öğrenilen</Text></View><View className="flex-1 rounded-2xl border border-amber-200 bg-amber-50 p-4"><Text className="text-2xl font-bold text-amber-700">{data?.currentStreak ?? 0}🔥</Text><Text className="mt-1 text-xs font-medium text-amber-700">Günlük seri</Text></View></View>
    <Pressable accessibilityRole="button" accessibilityLabel="Öğrenme rotalarını aç" onPress={() => navigation.navigate('LearningPaths')} className="mt-4 flex-row items-center rounded-2xl border border-border bg-surface p-5"><Text className="mr-4 text-3xl">🧭</Text><View className="flex-1"><Text className="text-lg font-bold text-foreground">Kendi rotanı seç</Text><Text className="mt-1 text-sm leading-5 text-muted-foreground">Seyahat, iş, akademik veya sınav hedefinden ilerle.</Text></View><Text className="text-xl text-primary">→</Text></Pressable>
    <Pressable accessibilityRole="button" accessibilityLabel="Kişisel pratik seansını aç" onPress={() => navigation.navigate('PracticeSession')} className="mt-4 flex-row items-center rounded-3xl bg-primary-soft p-5"><Text className="mr-4 text-3xl">⚡</Text><View className="flex-1"><Text className="text-lg font-bold text-foreground">Kişisel pratik seansı</Text><Text className="mt-1 text-sm leading-5 text-muted-foreground">Tek akışta tekrar, cümle, eşleştirme ve yazma.</Text></View><Text className="text-xl text-primary">→</Text></Pressable>
    <View className="mt-4 rounded-3xl bg-primary p-6"><Text className="text-xs font-bold uppercase tracking-widest text-blue-100">Kişisel koç</Text><Text className="mt-2 text-2xl font-bold text-white">{data?.coachTitle ?? 'Bugünün mini görevi'}</Text><Text className="mt-2 leading-5 text-blue-100">{data?.coachMessage ?? 'Kısa bir tekrar ile ilerlemeni koru.'}</Text><Pressable accessibilityRole="button" accessibilityLabel="Günün seansını başlat" onPress={() => navigation.navigate('DailyMission')} className="mt-5 items-center rounded-2xl bg-white py-4"><Text className="font-bold text-primary">{data?.recommendedSessionSize ?? 5} kelimelik seansı başlat</Text></Pressable></View>
    {weeklyStats.data ? <View className="mt-4 rounded-2xl border border-border bg-surface p-5"><View className="flex-row items-center justify-between"><Text className="text-lg font-bold text-foreground">Son 7 gün</Text><Text className="text-xs font-semibold text-muted-foreground">ÖĞRENME ÖZETİ</Text></View><View className="mt-5 flex-row justify-between"><View><Text className="text-2xl font-bold text-foreground">{weeklyStats.data.totalReviews}</Text><Text className="mt-1 text-xs text-muted-foreground">Tekrar</Text></View><View><Text className="text-2xl font-bold text-foreground">%{weeklyStats.data.successPercent}</Text><Text className="mt-1 text-xs text-muted-foreground">Başarı</Text></View><View><Text className="text-2xl font-bold text-foreground">{weeklyStats.data.learnedWords}</Text><Text className="mt-1 text-xs text-muted-foreground">Aktif gün</Text></View></View></View> : null}
    {data ? <View className="mt-4 rounded-2xl border border-border bg-surface p-5"><View className="flex-row items-center justify-between"><Text className="text-lg font-bold text-foreground">Haftalık hedef</Text><Text className="text-sm font-bold text-primary">{data.weeklyReviewProgress}/{data.weeklyReviewGoal}</Text></View><View className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><View className="h-2 rounded-full bg-primary" style={{ width: `${Math.min(1, data.weeklyReviewProgress / Math.max(1, data.weeklyReviewGoal)) * 100}%` }} /></View><Text className="mt-3 text-xs text-muted-foreground">Bu hafta düzenli tekrarlarla hedefini tamamla.</Text></View> : null}
    {data?.achievements?.length ? <View className="mt-4 rounded-2xl border border-border bg-surface p-5"><View className="flex-row items-center justify-between"><Text className="text-lg font-bold text-foreground">Rozetlerin</Text><Text className="text-xs font-semibold text-muted-foreground">{data.achievements.filter((item) => item.unlocked).length}/{data.achievements.length} AÇILDI</Text></View><View className="mt-4 flex-row gap-2">{data.achievements.map((item) => <View key={item.key} accessibilityLabel={`${item.title}: ${item.unlocked ? 'açıldı' : 'kilitli'}`} className={`flex-1 items-center rounded-2xl p-3 ${item.unlocked ? 'bg-amber-50' : 'bg-slate-50'}`}><Text className="text-xl">{item.unlocked ? '🏅' : '🔒'}</Text><Text numberOfLines={1} className={`mt-2 text-center text-[10px] font-bold ${item.unlocked ? 'text-amber-700' : 'text-muted-foreground'}`}>{item.title}</Text></View>)}</View></View> : null}
    {!entitlement.data?.isPremium ? <Pressable accessibilityRole="button" accessibilityLabel="Premium paketlerini gör" onPress={() => navigation.navigate('Premium')} className="mt-4 rounded-2xl bg-foreground p-5"><View className="flex-row items-center justify-between"><Text className="text-lg font-bold text-white">Daha hızlı ilerle</Text><Text className="text-xl text-amber-300">→</Text></View><Text className="mt-1 text-sm text-white/65">Premium ile tüm seviyeleri ve sınırsız çalışmayı aç.</Text></Pressable> : null}
    <Text className="mb-3 mt-7 text-xs font-bold uppercase tracking-widest text-muted-foreground">Hızlı erişim</Text><View className="flex-row gap-3"><Pressable accessibilityRole="button" accessibilityLabel="Quiz başlat" onPress={() => navigation.navigate('QuizStart')} className="flex-1 rounded-2xl border border-border bg-surface p-5"><Text className="text-2xl">✦</Text><Text className="mt-3 font-bold text-foreground">Mini quiz</Text><Text className="mt-1 text-xs leading-4 text-muted-foreground">Bilgini test et</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Cümle challenge aç" onPress={() => navigation.navigate('SentenceChallenge')} className="flex-1 rounded-2xl border border-border bg-surface p-5"><Text className="text-2xl">✍️</Text><Text className="mt-3 font-bold text-foreground">Cümle tamamla</Text><Text className="mt-1 text-xs leading-4 text-muted-foreground">Bağlamı öğren</Text></Pressable></View><View className="mt-3 flex-row gap-3"><Pressable accessibilityRole="button" accessibilityLabel="Yazma pratiği aç" onPress={() => navigation.navigate('WritingChallenge')} className="flex-1 rounded-2xl bg-primary-soft p-5"><Text className="text-2xl">⌨️</Text><Text className="mt-3 font-bold text-foreground">Yazarak hatırla</Text><Text className="mt-1 text-xs leading-4 text-muted-foreground">Aktif cevap ver</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Eşleştirme pratiği aç" onPress={() => navigation.navigate('MatchingChallenge')} className="flex-1 rounded-2xl bg-amber-50 p-5"><Text className="text-2xl">🔗</Text><Text className="mt-3 font-bold text-foreground">Eşleştir</Text><Text className="mt-1 text-xs leading-4 text-muted-foreground">Anlamı bul</Text></Pressable></View><View className="mt-3 flex-row gap-3"><Pressable accessibilityRole="button" accessibilityLabel="Haftalık liderlik panosunu aç" onPress={() => navigation.navigate('Leaderboard')} className="flex-1 rounded-2xl bg-amber-50 p-5"><Text className="text-2xl">🏆</Text><Text className="mt-3 font-bold text-foreground">Mavi Lig</Text><Text className="mt-1 text-xs leading-4 text-muted-foreground">Haftalık XP yarışına katıl</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Kelime kataloğunu aç" onPress={() => navigation.navigate('Vocabulary')} className="flex-1 rounded-2xl border border-border bg-surface p-5"><Text className="text-2xl">⌕</Text><Text className="mt-3 font-bold text-foreground">Katalog</Text><Text className="mt-1 text-xs leading-4 text-muted-foreground">Yeni kelimeler keşfet</Text></Pressable></View>
  </ScrollView>;
}
