import { useQuery } from '@tanstack/react-query';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { api } from '../../lib/api';

const icons: Record<string, string> = { 'full-course': '🇬🇧', pronunciation: '🗣️', travel: '✈️', business: '💼', academic: '🎓', exam: '🏅', culture: '📰' };
export function LearningPathsScreen({ navigation }: { navigation: { goBack: () => void; navigate: (route: 'Learn') => void } }) {
  const query = useQuery({ queryKey: ['learning-paths'], queryFn: api.learningPaths });
  return <ScrollView className="flex-1 bg-background px-5 pt-14" contentContainerStyle={{ paddingBottom: 48 }}><Pressable onPress={navigation.goBack}><Text className="font-semibold text-primary">‹ Geri</Text></Pressable><Text accessibilityRole="header" className="mt-7 text-4xl font-bold text-foreground">Hedefini seç.</Text><Text className="mt-2 text-base leading-6 text-muted-foreground">Sana en uygun rotayı seçelim; öğrenme akışın bu alana göre şekillensin.</Text>{query.isLoading ? <Text className="mt-8 text-muted-foreground">Rotalar hazırlanıyor…</Text> : <View className="mt-7 gap-3">{(query.data ?? []).map(path => <Pressable key={path.key} accessibilityRole="button" accessibilityLabel={`${path.title} rotasını seç`} onPress={() => navigation.navigate('Learn')} className={`flex-row items-center overflow-hidden rounded-2xl border p-4 ${path.recommended ? 'border-primary bg-primary-soft' : 'border-border bg-surface'}`}><Text className="mr-4 text-3xl">{icons[path.key] ?? '📚'}</Text><View className="flex-1"><View className="flex-row items-center justify-between"><Text className="text-lg font-bold text-foreground">{path.title}</Text>{path.recommended ? <Text className="rounded-full bg-primary px-2 py-1 text-[10px] font-bold text-white">ÖNERİLEN</Text> : null}</View><Text className="mt-1 leading-5 text-muted-foreground">{path.description}</Text></View></Pressable>)}</View>}</ScrollView>;
}
