import { FormEvent, useEffect, useMemo, useState } from 'react';
import { adminApi, AuditItem, ContentItem, Overview, QueueItem, tokenRole, tokenStore, VocabularyInput, VocabularyPage } from './api';

const emptyForm: VocabularyInput = { term: '', pronunciation: '', partOfSpeech: 'noun', definition: '', translation: '', level: 'A1', category: 'Daily Life', exampleSentence: '' };
const dateLabel = (value: string) => new Intl.DateTimeFormat('tr-TR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));

export function App() {
  const [token, setToken] = useState(tokenStore.get());
  if (!token) return <Login onLogin={(value) => { tokenStore.set(value); setToken(value); }} />;
  return <Dashboard token={token} onLogout={() => { tokenStore.clear(); setToken(null); }} />;
}

function Login({ onLogin }: { onLogin: (token: string) => void }) {
  const [email, setEmail] = useState('test@example.com'); const [password, setPassword] = useState('Test1234!'); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { const result = await adminApi.login(email, password); if (!['Admin', 'Reviewer', 'Editor'].includes(tokenRole(result.accessToken))) throw new Error('Bu hesap admin paneline yetkili değil.'); onLogin(result.accessToken); } catch (e) { setError(e instanceof Error ? e.message : 'Giriş başarısız.'); } finally { setLoading(false); } };
  return <main className="login-shell"><section className="login-card"><div className="brand-mark">EL</div><p className="eyebrow">ENGLISH LEARNING</p><h1>İçerik stüdyosuna hoş geldin</h1><p className="muted">Kelime kataloğunu, inceleme kuyruğunu ve yayın akışını tek yerden yönet.</p><form onSubmit={submit}><label>E-posta<input value={email} onChange={(e) => setEmail(e.target.value)} type="email" required /></label><label>Şifre<input value={password} onChange={(e) => setPassword(e.target.value)} type="password" required /></label>{error ? <div className="alert error">{error}</div> : null}<button className="primary full" disabled={loading}>{loading ? 'Giriş yapılıyor…' : 'Admin paneline gir'}</button></form></section></main>;
}

function Dashboard({ token, onLogout }: { token: string; onLogout: () => void }) {
  type View = 'overview' | 'catalog' | 'content' | 'queue' | 'audit';
  const [view, setView] = useState<View>('overview'); const [overview, setOverview] = useState<Overview>(); const [queue, setQueue] = useState<QueueItem[]>([]); const [audit, setAudit] = useState<AuditItem[]>([]); const [filter, setFilter] = useState(''); const [form, setForm] = useState(emptyForm); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const role = tokenRole(token); const isAdmin = role === 'Admin';
  const refresh = async () => { try { setError(''); const q = await adminApi.queue(filter); setQueue(q); if (isAdmin) { const [o, a] = await Promise.all([adminApi.overview(), adminApi.audit()]); setOverview(o); setAudit(a); } } catch (e) { setError(e instanceof Error ? e.message : 'Veriler yüklenemedi.'); } };
  useEffect(() => { void refresh(); }, [filter]);
  const cards = useMemo(() => [['Kullanıcı', overview?.users ?? '—'], ['Yayınlanan kelime', overview ? `${overview.publishedVocabularyWords}/${overview.vocabularyCapacity}` : '—'], ['Quiz başarı', overview ? `%${Math.round(overview.quizAccuracyPercent)}` : '—'], ['Tekrar başarı', overview ? `%${Math.round(overview.reviewSuccessPercent)}` : '—']], [overview]);
  const act = async (action: () => Promise<void>, success: string) => { setBusy(true); setError(''); try { await action(); setMessage(success); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'İşlem tamamlanamadı.'); } finally { setBusy(false); } };
  const create = async (event: FormEvent) => { event.preventDefault(); await act(() => adminApi.createVocabulary(form).then(() => undefined), 'Taslak içerik oluşturuldu.'); setForm(emptyForm); };
  const nav = (key: View, label: string, badge?: number) => <button type="button" className={`nav-item ${view === key ? 'active' : ''}`} onClick={() => setView(key)}>{label}{badge === undefined ? null : <span>{badge}</span>}</button>;
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark small">EL</div><div><strong>English Learning</strong><span>Content Studio</span></div></div><nav>{nav('overview', 'Genel bakış')}{isAdmin ? nav('catalog', 'Kelime kataloğu', overview?.vocabularyWords) : null}{isAdmin ? nav('content', 'Ders içerikleri') : null}{nav('queue', 'İçerik kuyruğu', queue.length)}{isAdmin ? nav('audit', 'Audit geçmişi') : null}</nav><div className="sidebar-footer"><span className="role-pill">{role}</span><button className="ghost" onClick={onLogout}>Çıkış yap</button></div></aside><main className="content"><header className="topbar"><div><p className="eyebrow">ADMIN WORKSPACE</p><h1>{view === 'catalog' ? 'Kelime kataloğu' : view === 'content' ? 'Ders içerikleri' : view === 'queue' ? 'İnceleme kuyruğu' : view === 'audit' ? 'Audit geçmişi' : 'İçerik operasyonu'}</h1></div><button className="ghost" onClick={() => void refresh()}>Yenile ↻</button></header>{message ? <div className="alert success">{message}</div> : null}{error ? <div className="alert error">{error}</div> : null}{view === 'catalog' && isAdmin ? <VocabularyCatalog /> : view === 'content' && isAdmin ? <ContentStudio /> : view === 'queue' ? <QueuePanel queue={queue} filter={filter} setFilter={setFilter} busy={busy} act={act} role={role} /> : view === 'audit' && isAdmin ? <AuditPanel audit={audit} /> : <><section className="stats-grid">{cards.map(([label, value]) => <div className="stat-card" key={label}><span>{label}</span><strong>{value}</strong><small>Canlı veriden</small></div>)}</section><div className="workspace-grid"><QueuePanel queue={queue} filter={filter} setFilter={setFilter} busy={busy} act={act} role={role} /><CreatePanel form={form} setForm={setForm} create={create} busy={busy} /></div><AuditPanel audit={audit} /></>}</main></div>;
}

function QueuePanel({ queue, filter, setFilter, busy, act, role = 'Admin' }: { queue: QueueItem[]; filter: string; setFilter: (value: string) => void; busy: boolean; act: (action: () => Promise<void>, success: string) => Promise<void>; role?: string }) { const canReview = role === 'Admin' || role === 'Reviewer'; return <section className="panel"><div className="panel-header"><div><p className="eyebrow">WORKFLOW</p><h2>İnceleme kuyruğu</h2></div><select value={filter} onChange={(e) => setFilter(e.target.value)}><option value="">Tüm taslaklar</option><option value="Draft">Taslak</option><option value="InReview">İncelemede</option><option value="Rejected">Reddedildi</option></select></div>{queue.length === 0 ? <div className="empty">İnceleme bekleyen içerik yok.</div> : <div className="queue">{queue.map(item => <article className="queue-item" key={item.id}><div className="queue-copy"><div className="item-title"><strong>{item.term}</strong><span className={`status ${item.status.toLowerCase()}`}>{item.status}</span></div><p>{item.translation} · {item.level} · {item.category}</p></div><div className="actions">{item.status === 'Draft' ? <button className="secondary" disabled={busy} onClick={() => void act(() => adminApi.submitReview(item.id), 'İçerik incelemeye gönderildi.')}>İncelemeye gönder</button> : null}{canReview && item.status === 'InReview' ? <><button className="secondary danger" disabled={busy} onClick={() => void act(() => adminApi.reject(item.id), 'İçerik reddedildi.')}>Reddet</button><button className="primary" disabled={busy} onClick={() => void act(() => adminApi.publish(item.id), 'İçerik yayınlandı.')}>Yayınla</button></> : null}</div></article>)}</div>}</section>; }
function CreatePanel({ form, setForm, create, busy }: { form: VocabularyInput; setForm: (value: VocabularyInput) => void; create: (event: FormEvent) => Promise<void>; busy: boolean }) { return <section className="panel create-panel"><div className="panel-header"><div><p className="eyebrow">CONTENT</p><h2>Yeni kelime taslağı</h2></div></div><form onSubmit={create} className="form-grid"><label>Kelime<input value={form.term} onChange={(e) => setForm({ ...form, term: e.target.value })} required /></label><label>Çeviri<input value={form.translation} onChange={(e) => setForm({ ...form, translation: e.target.value })} required /></label><label>Seviye<select value={form.level} onChange={(e) => setForm({ ...form, level: e.target.value })}><option>A1</option><option>A2</option><option>B1</option><option>B2</option><option>C1</option><option>C2</option></select></label><label>Kategori<input value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} required /></label><label className="wide">Tanım<textarea value={form.definition} onChange={(e) => setForm({ ...form, definition: e.target.value })} required /></label><label className="wide">Örnek cümle<textarea value={form.exampleSentence} onChange={(e) => setForm({ ...form, exampleSentence: e.target.value })} /></label><button className="primary wide" disabled={busy}>Taslak olarak kaydet</button></form></section>; }
function AuditPanel({ audit }: { audit: AuditItem[] }) { return <section className="panel audit-panel"><div className="panel-header"><div><p className="eyebrow">TRACEABILITY</p><h2>Son işlemler</h2></div><span className="muted">Audit log</span></div><div className="audit-list">{audit.slice(0, 8).map(item => <div className="audit-row" key={item.id}><span className="audit-dot" /><div><strong>{item.action}</strong><span>{item.entityType} · {item.entityId?.slice(0, 8) ?? '—'}</span></div><time>{dateLabel(item.createdAtUtc)}</time></div>)}</div></section>; }
function VocabularyCatalog() { const [data, setData] = useState<VocabularyPage>(); const [search, setSearch] = useState(''); const [level, setLevel] = useState(''); const [status, setStatus] = useState(''); const [page, setPage] = useState(1); const [error, setError] = useState(''); useEffect(() => { setError(''); void adminApi.vocabulary({ search, level, status, page, pageSize: 50 }).then(setData).catch(e => setError(e instanceof Error ? e.message : 'Katalog yüklenemedi.')); }, [search, level, status, page]); return <section className="panel catalog-panel"><div className="catalog-toolbar"><input placeholder="Kelime, çeviri veya tanım ara…" value={search} onChange={e => { setPage(1); setSearch(e.target.value); }} /><select value={level} onChange={e => { setPage(1); setLevel(e.target.value); }}><option value="">Tüm seviyeler</option>{['A1','A2','B1','B2','C1','C2'].map(x => <option key={x}>{x}</option>)}</select><select value={status} onChange={e => { setPage(1); setStatus(e.target.value); }}><option value="">Tüm durumlar</option><option>Published</option><option>Draft</option><option>InReview</option><option>Rejected</option></select></div>{error ? <div className="alert error">{error}</div> : null}<p className="muted catalog-count">{data ? `${data.totalCount} kelime bulundu` : 'Katalog yükleniyor…'}</p><div className="catalog-table-wrap"><table className="catalog-table"><thead><tr><th>Kelime</th><th>Çeviri</th><th>Seviye</th><th>Kategori</th><th>Durum</th><th>Tanım</th></tr></thead><tbody>{data?.items.map(item => <tr key={item.id}><td><strong>{item.term}</strong><small>{item.partOfSpeech}</small></td><td>{item.translation}</td><td>{item.level}</td><td>{item.category}</td><td><span className={`status ${item.status.toLowerCase()}`}>{item.status}</span></td><td>{item.definition}</td></tr>)}</tbody></table>{data?.items.length === 0 ? <div className="empty">Sonuç bulunamadı.</div> : null}</div>{data ? <div className="pagination"><button className="secondary" disabled={page <= 1} onClick={() => setPage(page - 1)}>← Önceki</button><span>Sayfa {data.page} / {Math.max(1, data.totalPages)}</span><button className="secondary" disabled={page >= data.totalPages} onClick={() => setPage(page + 1)}>Sonraki →</button></div> : null}</section>; }
function ContentStudio() { const [items, setItems] = useState<ContentItem[]>([]); const [status, setStatus] = useState(''); const [error, setError] = useState(''); const [form, setForm] = useState({ key: '', title: '', type: 'grammar', level: 'A1', category: 'grammar', payloadJson: '{"rules":[],"exercises":[]}' }); const reload = () => adminApi.content(status).then(setItems).catch(e => setError(e instanceof Error ? e.message : 'Ders içerikleri yüklenemedi.')); useEffect(() => { void reload(); }, [status]); const create = async (event: FormEvent) => { event.preventDefault(); setError(''); try { await adminApi.createContent(form); setForm({ ...form, key: '', title: '' }); await reload(); } catch (e) { setError(e instanceof Error ? e.message : 'İçerik oluşturulamadı.'); } }; return <section className="panel catalog-panel"><div className="panel-header"><div><p className="eyebrow">GRAMMAR & LESSONS</p><h2>Öğrenme içerikleri</h2></div><select value={status} onChange={e => setStatus(e.target.value)}><option value="">Tüm durumlar</option><option>Draft</option><option>InReview</option><option>Published</option><option>Archived</option></select></div>{error ? <div className="alert error">{error}</div> : null}<form onSubmit={create} className="form-grid"><label>Anahtar<input value={form.key} onChange={e => setForm({ ...form, key: e.target.value })} required placeholder="grammar.present-simple" /></label><label>Başlık<input value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} required /></label><label>Seviye<select value={form.level} onChange={e => setForm({ ...form, level: e.target.value })}><option>A1</option><option>A2</option><option>B1</option><option>B2</option><option>C1</option><option>C2</option></select></label><label>Kategori<input value={form.category} onChange={e => setForm({ ...form, category: e.target.value })} required /></label><label className="wide">İçerik JSON<textarea value={form.payloadJson} onChange={e => setForm({ ...form, payloadJson: e.target.value })} required /></label><button className="primary wide">Taslak içerik oluştur</button></form><div className="catalog-table-wrap"><table className="catalog-table"><thead><tr><th>Başlık</th><th>Tür</th><th>Seviye</th><th>Kategori</th><th>Durum</th><th>Versiyon</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td><strong>{item.title}</strong><small>{item.key}</small></td><td>{item.type}</td><td>{item.level}</td><td>{item.category}</td><td><span className={`status ${item.status.toLowerCase()}`}>{item.status}</span></td><td>v{item.version}</td></tr>)}</tbody></table>{items.length === 0 ? <div className="empty">Henüz içerik kaydı yok. İlk gramer derslerini bu stüdyo üzerinden yayınlayacağız.</div> : null}</div></section>; }
