import { useState } from 'react';
import { Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { api } from '../../lib/api';
import { useAuthStore } from '../../store/auth-store';

export function LoginScreen({ navigation }: { navigation: { navigate: (route: 'Register') => void } }) {
  const signIn = useAuthStore((s) => s.signIn); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async () => { setError(''); setLoading(true); try { await signIn(await api.login({ email: email.trim(), password })); } catch (e) { setError((e as { message?: string }).message ?? 'Giriş yapılamadı.'); } finally { setLoading(false); } };
  return <ScrollView className="flex-1 bg-background px-6" contentContainerStyle={{ paddingBottom: 48, paddingTop: 56 }}><View className="h-14 w-14 items-center justify-center rounded-2xl bg-primary"><Text className="text-2xl font-bold text-white">W</Text></View><Text className="mt-8 text-4xl font-bold leading-tight text-foreground">Öğrenmeye devam et.</Text><Text className="mt-3 text-base leading-6 text-muted-foreground">Kişisel kelime koçun kaldığın yerden hazır.</Text><View className="mt-9 rounded-3xl border border-border bg-surface p-5"><Text className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Hesabına giriş yap</Text><TextInput accessibilityLabel="E-posta" autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="E-posta adresin" placeholderTextColor="#94A3B8" className="mt-5 rounded-2xl border border-border bg-background px-4 py-4 text-foreground" /><TextInput accessibilityLabel="Şifre" secureTextEntry value={password} onChangeText={setPassword} placeholder="Şifren" placeholderTextColor="#94A3B8" className="mt-3 rounded-2xl border border-border bg-background px-4 py-4 text-foreground" />{error ? <Text accessibilityRole="alert" className="mt-3 rounded-xl bg-red-50 p-3 text-red-700">{error}</Text> : null}<Pressable accessibilityRole="button" accessibilityLabel="Giriş yap" disabled={loading} onPress={submit} className="mt-5 items-center rounded-2xl bg-primary py-4"><Text className="font-bold text-white">{loading ? 'Giriş yapılıyor…' : 'Giriş yap'}</Text></Pressable></View><Pressable accessibilityRole="button" accessibilityLabel="Yeni hesap oluştur" onPress={() => navigation.navigate('Register')} className="mt-7 items-center"><Text className="text-sm text-muted-foreground">Henüz hesabın yok mu? <Text className="font-bold text-primary">Kayıt ol</Text></Text></Pressable></ScrollView>;
}
