import { useState } from 'react';
import { Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { api } from '../../lib/api';
import { useAuthStore } from '../../store/auth-store';

export function RegisterScreen({ navigation }: { navigation: { goBack: () => void } }) {
  const signIn = useAuthStore((s) => s.signIn); const [displayName, setDisplayName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async () => { setError(''); setLoading(true); try { await signIn(await api.register({ displayName: displayName.trim(), email: email.trim(), password })); } catch (e) { setError((e as { message?: string }).message ?? 'Kayıt oluşturulamadı.'); } finally { setLoading(false); } };
  return <ScrollView className="flex-1 bg-background px-6" contentContainerStyle={{ paddingBottom: 48, paddingTop: 48 }}><Pressable accessibilityRole="button" accessibilityLabel="Geri dön" onPress={navigation.goBack} className="self-start rounded-full bg-surface px-4 py-2"><Text className="font-semibold text-primary">‹  Geri</Text></Pressable><Text className="mt-8 text-4xl font-bold leading-tight text-foreground">Kendi öğrenme planını oluştur.</Text><Text className="mt-3 text-base leading-6 text-muted-foreground">Birkaç bilgiyle sana uygun günlük ritmi hazırlayalım.</Text><View className="mt-8 rounded-3xl border border-border bg-surface p-5"><TextInput accessibilityLabel="Ad" value={displayName} onChangeText={setDisplayName} placeholder="Adın" placeholderTextColor="#94A3B8" className="rounded-2xl border border-border bg-background px-4 py-4 text-foreground" /><TextInput accessibilityLabel="E-posta" autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="E-posta adresin" placeholderTextColor="#94A3B8" className="mt-3 rounded-2xl border border-border bg-background px-4 py-4 text-foreground" /><TextInput accessibilityLabel="Şifre" secureTextEntry value={password} onChangeText={setPassword} placeholder="Güçlü bir şifre oluştur" placeholderTextColor="#94A3B8" className="mt-3 rounded-2xl border border-border bg-background px-4 py-4 text-foreground" />{error ? <Text accessibilityRole="alert" className="mt-3 rounded-xl bg-red-50 p-3 text-red-700">{error}</Text> : null}<Pressable accessibilityRole="button" accessibilityLabel="Kayıt ol" disabled={loading} onPress={submit} className="mt-5 items-center rounded-2xl bg-primary py-4"><Text className="font-bold text-white">{loading ? 'Hesap oluşturuluyor…' : 'Hesap oluştur'}</Text></Pressable></View></ScrollView>;
}
