import { useState } from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { api, PlacementTest, PlacementResult } from '../../lib/api';

export function PlacementTestScreen({ navigation }: { navigation: { goBack: () => void } }) {
  const [test, setTest] = useState<PlacementTest | null>(null);
  const [result, setResult] = useState<PlacementResult | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const current = test?.questions.find((question) => !question.answered);
  const start = async () => { setBusy(true); setError(null); try { setTest(await api.startPlacement(8)); } catch { setError('Seviye testi başlatılamadı.'); } finally { setBusy(false); } };
  const answer = async (key: string) => { if (!test || !current || busy) return; setBusy(true); try { await api.answerPlacement(test.id, current.id, key); setTest(await api.getPlacement(test.id)); } catch { setError('Cevabın kaydedilemedi.'); } finally { setBusy(false); } };
  const complete = async () => { if (!test) return; setBusy(true); try { setResult(await api.completePlacement(test.id)); } catch { setError('Sonuç hesaplanamadı.'); } finally { setBusy(false); } };
  if (result) return <View className="flex-1 bg-background px-5 pt-16"><Text className="text-sm font-bold uppercase tracking-widest text-primary">Seviye raporu</Text><Text className="mt-4 text-4xl font-bold text-foreground">{result.estimatedLevel}</Text><Text className="mt-3 text-lg text-muted-foreground">{result.scorePercent}% başarı · {result.correctCount}/{result.questionCount} doğru</Text><Text className="mt-6 leading-6 text-muted-foreground">Bu sonuç, sana uygun dersleri ve pratik zorluğunu kişiselleştirmek için kullanılacak.</Text><Pressable onPress={navigation.goBack} className="mt-8 items-center rounded-2xl bg-primary py-4"><Text className="font-bold text-white">Öğrenmeye başla</Text></Pressable></View>;
  if (!test) return <View className="flex-1 bg-background px-5 pt-16"><Pressable onPress={navigation.goBack}><Text className="font-semibold text-primary">‹ Geri</Text></Pressable><Text className="mt-10 text-4xl font-bold text-foreground">Seviyeni keşfet</Text><Text className="mt-4 text-base leading-6 text-muted-foreground">8 kısa soruyla rotanı ve günlük hedefini sana göre ayarlayalım.</Text>{error ? <Text className="mt-5 rounded-2xl bg-red-50 p-4 text-red-700">{error}</Text> : null}<Pressable disabled={busy} onPress={() => void start()} className="mt-8 items-center rounded-2xl bg-primary py-4"><Text className="font-bold text-white">{busy ? 'Hazırlanıyor…' : 'Teste başla'}</Text></Pressable></View>;
  if (!current) return <View className="flex-1 items-center justify-center bg-background px-5"><Text className="text-2xl font-bold text-foreground">Tüm sorular tamamlandı</Text><Pressable disabled={busy} onPress={() => void complete()} className="mt-6 rounded-2xl bg-primary px-8 py-4"><Text className="font-bold text-white">Sonucu gör</Text></Pressable></View>;
  return <ScrollView className="flex-1 bg-background px-5 pt-16" contentContainerStyle={{ paddingBottom: 48 }}><Text className="text-sm font-bold uppercase tracking-widest text-primary">Seviye testi · {test.answeredCount + 1}/{test.questionCount}</Text><View className="mt-5 h-2 overflow-hidden rounded-full bg-slate-200"><View className="h-2 rounded-full bg-primary" style={{ width: `${(test.answeredCount / test.questionCount) * 100}%` }} /></View><Text className="mt-10 text-2xl font-bold text-foreground">{current.prompt}</Text><View className="mt-8 gap-3">{current.options.map((option) => <Pressable key={option.key} disabled={busy} onPress={() => void answer(option.key)} className="rounded-2xl border border-border bg-surface p-5"><Text className="text-base font-semibold text-foreground">{option.key}. {option.text}</Text></Pressable>)}</View>{error ? <Text className="mt-5 text-red-700">{error}</Text> : null}</ScrollView>;
}
