import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { FlatList, Pressable, Text, TextInput, View } from 'react-native';
import { PronunciationButton } from '../../components/PronunciationButton';
import { api } from '../../lib/api';

export function VocabularyScreen({ navigation }: { navigation: { navigate: (route: 'WordDetail', params: { id: string }) => void; goBack: () => void } }) {
  const [level, setLevel] = useState<string>(); const [search, setSearch] = useState('');
  const levels = useQuery({ queryKey: ['vocabulary', 'levels'], queryFn: api.vocabularyLevels });
  const words = useQuery({ queryKey: ['vocabulary', 'words', level, search], queryFn: () => api.words({ level, search: search.trim() || undefined }) });
  const items = words.data?.items ?? [];
  return <View className="flex-1 bg-background px-5 pt-14"><Pressable accessibilityRole="button" accessibilityLabel="Geri dön" onPress={navigation.goBack} className="self-start rounded-full bg-surface px-4 py-2"><Text className="font-semibold text-primary">‹  Geri</Text></Pressable><Text accessibilityRole="header" className="mt-7 text-4xl font-bold leading-tight text-foreground">Kelime keşfet.</Text><Text className="mt-2 text-base text-muted-foreground">Seviyene uygun kelimeleri bul, dinle ve kaydet.</Text><TextInput accessibilityLabel="Kelime ara" value={search} onChangeText={setSearch} placeholder="Kelime veya anlam ara" placeholderTextColor="#94A3B8" className="mt-6 rounded-2xl border border-border bg-surface px-4 py-4 text-foreground" /><Text className="mb-2 mt-6 text-xs font-bold uppercase tracking-widest text-muted-foreground">Seviye filtresi</Text><FlatList horizontal showsHorizontalScrollIndicator={false} data={levels.data ?? []} keyExtractor={(item) => item.value} className="max-h-12" contentContainerStyle={{ gap: 8 }} renderItem={({ item }) => <Pressable accessibilityRole="button" accessibilityLabel={`${item.label} seviyesini filtrele`} onPress={() => setLevel(level === item.value ? undefined : item.value)} className={`rounded-full border px-5 py-3 ${level === item.value ? 'border-primary bg-primary' : 'border-border bg-surface'}`}><Text className={level === item.value ? 'font-bold text-white' : 'font-semibold text-foreground'}>{item.label}</Text></Pressable>} /><Text className="mb-3 mt-6 text-sm font-medium text-muted-foreground">{words.isFetching ? 'Kelimeler yükleniyor…' : `${items.length} kelime bulundu`}</Text>{words.isError ? <Text accessibilityRole="alert" className="rounded-2xl bg-red-50 p-4 text-red-700">Kelimeler yüklenemedi. Tekrar deneyin.</Text> : <FlatList className="flex-1" contentContainerStyle={{ paddingBottom: 48 }} data={items} keyExtractor={(item) => item.id} ListEmptyComponent={<Text className="py-10 text-center text-muted-foreground">Bu filtreyle kelime bulunamadı.</Text>} renderItem={({ item }) => <Pressable accessibilityRole="button" accessibilityLabel={`${item.term} kelime detayını aç`} onPress={() => navigation.navigate('WordDetail', { id: item.id })} className="mb-3 rounded-2xl border border-border bg-surface p-5"><View className="flex-row items-start justify-between"><View className="flex-1 pr-3"><Text className="text-xl font-bold text-foreground">{item.term}</Text><Text className="mt-1 text-sm text-muted-foreground">{item.translation}</Text></View><Text className="rounded-full bg-primary-soft px-3 py-1 text-xs font-bold text-primary">{item.level}</Text></View><View className="mt-4 flex-row items-center justify-between"><Text className="text-xs font-medium text-muted-foreground">{item.partOfSpeech || 'Kelime'}</Text><PronunciationButton text={item.term} label={`${item.term} telaffuzunu dinle`} /></View></Pressable>} />}</View>;
}
