import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { FlatList, Pressable, Text, TextInput, View } from 'react-native';
import { api } from '../../lib/api';

export function VocabularyScreen({ navigation }: { navigation: { navigate: (route: 'WordDetail', params: { id: string }) => void; goBack: () => void } }) {
  const [level, setLevel] = useState<string>();
  const [search, setSearch] = useState('');
  const levels = useQuery({ queryKey: ['vocabulary', 'levels'], queryFn: api.vocabularyLevels });
  const words = useQuery({ queryKey: ['vocabulary', 'words', level, search], queryFn: () => api.words({ level, search: search.trim() || undefined }) });
  const items = words.data?.items ?? [];
  return <View className="flex-1 bg-background px-5 pt-14"><Pressable onPress={navigation.goBack} className="mb-4"><Text className="font-semibold text-blue-700">‹ Geri</Text></Pressable><Text className="text-3xl font-bold text-foreground">Kelime kataloğu</Text><Text className="mt-1 text-muted-foreground">Yeni kelimeler keşfet.</Text><TextInput value={search} onChangeText={setSearch} placeholder="Kelime ara" className="mt-5 rounded-2xl bg-white px-4 py-4 text-foreground" /><FlatList horizontal showsHorizontalScrollIndicator={false} data={levels.data ?? []} keyExtractor={(item) => item.value} className="mt-4 max-h-12" contentContainerStyle={{ gap: 8 }} renderItem={({ item }) => <Pressable onPress={() => setLevel(level === item.value ? undefined : item.value)} className={`rounded-full px-5 py-3 ${level === item.value ? 'bg-blue-600' : 'bg-white'}`}><Text className={level === item.value ? 'font-bold text-white' : 'font-semibold text-foreground'}>{item.label}</Text></Pressable>} /><Text className="mb-2 mt-5 text-sm text-muted-foreground">{words.isFetching ? 'Yükleniyor…' : `${items.length} kelime`}</Text>{words.isError ? <Text className="rounded-xl bg-red-50 p-4 text-red-700">Kelimeler yüklenemedi. Tekrar deneyin.</Text> : <FlatList data={items} keyExtractor={(item) => item.id} ListEmptyComponent={<Text className="py-10 text-center text-muted-foreground">Bu filtreyle kelime bulunamadı.</Text>} renderItem={({ item }) => <Pressable onPress={() => navigation.navigate('WordDetail', { id: item.id })} className="mb-3 rounded-2xl bg-white p-4"><View className="flex-row items-center justify-between"><Text className="text-lg font-bold text-foreground">{item.term}</Text><Text className="text-xs text-muted-foreground">{item.level}</Text></View><Text className="mt-1 text-muted-foreground">{item.translation}</Text>{item.partOfSpeech ? <Text className="mt-2 text-xs text-blue-700">{item.partOfSpeech}</Text> : null}</Pressable>} />}</View>;
}
