import { useState } from 'react';
import { Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { useMutation, useQuery } from '@tanstack/react-query';
import { api, ConversationScenario } from '../../lib/api';
import { PronunciationButton } from '../../components/PronunciationButton';

export function ConversationPracticeScreen({ navigation }: { navigation: { goBack: () => void } }) {
  const scenarios = useQuery({ queryKey: ['conversation-scenarios'], queryFn: () => api.conversationScenarios() });
  const [selected, setSelected] = useState<ConversationScenario | null>(null); const [transcript, setTranscript] = useState('');
  const assess = useMutation({ mutationFn: () => api.assessPronunciation(selected?.turns[1]?.english ?? '', transcript) });
  const active = selected ?? scenarios.data?.[0];
  return <ScrollView className="flex-1 bg-background px-5 pt-14" contentContainerStyle={{ paddingBottom: 56 }}><Pressable onPress={navigation.goBack}><Text className="font-semibold text-primary">‹ Geri</Text></Pressable><Text accessibilityRole="header" className="mt-8 text-4xl font-bold text-foreground">Konuşma pratiği</Text><Text className="mt-2 text-base leading-6 text-muted-foreground">Senaryoyu seç, cümleyi dinle, yüksek sesle tekrar et ve kendi sonucunu gör.</Text>{scenarios.isLoading ? <Text className="mt-8 text-muted-foreground">Senaryolar hazırlanıyor…</Text> : null}<View className="mt-7 gap-3">{scenarios.data?.map(scenario => <Pressable key={scenario.key} accessibilityRole="button" accessibilityState={{ selected: active?.key === scenario.key }} onPress={() => { setSelected(scenario); setTranscript(''); assess.reset(); }} className={`rounded-2xl border p-4 ${active?.key === scenario.key ? 'border-primary bg-primary-soft' : 'border-border bg-surface'}`}><View className="flex-row items-center justify-between"><Text className="font-bold text-foreground">{scenario.title}</Text><Text className="text-xs font-bold text-primary">{scenario.level}</Text></View><Text className="mt-1 text-sm text-muted-foreground">{scenario.description}</Text><Text className="mt-2 text-xs text-primary">Hedef: {scenario.goal}</Text></Pressable>)}</View>{active ? <View className="mt-7 rounded-3xl bg-surface p-6"><Text className="text-xs font-bold uppercase tracking-widest text-primary">DİYALOG VE TELAFFUZ</Text>{active.turns.map((turn, index) => <View key={`${turn.speaker}-${index}`} className="mt-5 border-b border-border pb-5"><Text className="text-xs font-bold text-muted-foreground">{turn.speaker.toUpperCase()} · {turn.focus}</Text><Text className="mt-2 text-xl font-bold text-foreground">{turn.english}</Text><Text className="mt-1 text-sm text-muted-foreground">{turn.turkish}</Text><View className="mt-3"><PronunciationButton text={turn.english} label="Cümleyi dinle" /></View>{index === active.turns.length - 1 ? <><TextInput accessibilityLabel="Söylediğin cümlenin metni" value={transcript} onChangeText={setTranscript} placeholder="Söylediğin cümleyi buraya yaz" placeholderTextColor="#94A3B8" multiline className="mt-4 rounded-2xl border border-border bg-background p-4 text-foreground" /><Pressable disabled={!transcript.trim() || assess.isPending} onPress={() => assess.mutate()} className="mt-3 items-center rounded-2xl bg-primary py-4"><Text className="font-bold text-white">{assess.isPending ? 'Değerlendiriliyor…' : 'Telaffuzumu değerlendir'}</Text></Pressable>{assess.data ? <View className="mt-4 rounded-2xl bg-primary-soft p-4"><Text className="text-2xl font-bold text-foreground">{assess.data.score}/100 · {assess.data.grade}</Text><Text className="mt-1 text-sm text-muted-foreground">{assess.data.feedback}</Text></View> : null}</> : null}</View>)}</View> : null}</ScrollView>;
}
