import { useState } from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { useQuery } from '@tanstack/react-query';
import { api, GrammarLesson } from '../../lib/api';

export function GrammarLabScreen({ navigation }: { navigation: { goBack: () => void } }) {
  const query = useQuery({ queryKey: ['grammar-lessons'], queryFn: () => api.grammarLessons() });
  const [selected, setSelected] = useState<GrammarLesson>();
  const [answers, setAnswers] = useState<Record<number, string>>({});
  const lessons = query.data ?? [];
  if (selected) return <ScrollView className="flex-1 bg-background px-5 pt-14" contentContainerStyle={{ paddingBottom: 48 }}><Pressable onPress={() => { setSelected(undefined); setAnswers({}); }}><Text className="font-semibold text-primary">‹ Gramer derslerine dön</Text></Pressable><Text className="mt-8 text-xs font-bold uppercase tracking-widest text-primary">{selected.level} · TÜRKÇE KARŞILAŞTIRMALI</Text><Text className="mt-3 text-3xl font-bold text-foreground">{selected.title}</Text><Text className="mt-4 leading-6 text-muted-foreground">{selected.summary}</Text><View className="mt-5 rounded-2xl bg-primary-soft p-4"><Text className="font-semibold text-primary">Türkçe notu</Text><Text className="mt-2 leading-6 text-foreground">{selected.contrastNote}</Text></View><Text className="mb-3 mt-7 text-xl font-bold text-foreground">Kural kartları</Text>{selected.rules.map(rule => <View key={rule.title} className="mb-3 rounded-2xl border border-border bg-surface p-4"><Text className="font-bold text-foreground">{rule.title}</Text><Text className="mt-2 leading-6 text-muted-foreground">{rule.explanation}</Text><Text className="mt-2 text-xs font-semibold text-primary">{rule.focus}</Text></View>)}<Text className="mb-3 mt-7 text-xl font-bold text-foreground">Mini pratik</Text>{selected.exercises.map((exercise, index) => <View key={exercise.prompt} className="mb-4 rounded-2xl bg-surface p-4"><Text className="font-semibold text-foreground">{exercise.prompt}</Text><View className="mt-3 gap-2">{exercise.options.map(option => <Pressable key={option} disabled={Boolean(answers[index])} onPress={() => setAnswers({ ...answers, [index]: option })} className={`rounded-xl border p-3 ${answers[index] === option ? option === exercise.answer ? 'border-green-600 bg-green-50' : 'border-red-600 bg-red-50' : 'border-border'}`}><Text className="font-medium text-foreground">{option}</Text></Pressable>)}</View>{answers[index] ? <Text className={`mt-3 font-semibold ${answers[index] === exercise.answer ? 'text-green-700' : 'text-red-700'}`}>{answers[index] === exercise.answer ? 'Doğru! ' : `Doğru cevap: ${exercise.answer}. `}{exercise.explanation}</Text> : null}</View>)}</ScrollView>;
  return <ScrollView className="flex-1 bg-background px-5 pt-14" contentContainerStyle={{ paddingBottom: 48 }}><Pressable onPress={navigation.goBack}><Text className="font-semibold text-primary">‹ Geri</Text></Pressable><Text className="mt-8 text-xs font-bold uppercase tracking-widest text-primary">GRAMER LABORATUVARI</Text><Text className="mt-3 text-3xl font-bold text-foreground">Türkçe düşün, İngilizce kur</Text><Text className="mt-3 leading-6 text-muted-foreground">Türkçe ile İngilizce arasındaki farkları örneklerle öğren, sonra hemen cümle içinde uygula.</Text>{query.isError ? <Text className="mt-6 text-red-700">Gramer içerikleri yüklenemedi. Tekrar deneyin.</Text> : null}<View className="mt-7 gap-3">{lessons.map(lesson => <Pressable key={lesson.key} onPress={() => setSelected(lesson)} className="rounded-2xl border border-border bg-surface p-5"><View className="flex-row items-center justify-between"><Text className="text-xs font-bold text-primary">{lesson.level}</Text><Text className="text-xl">→</Text></View><Text className="mt-2 text-lg font-bold text-foreground">{lesson.title}</Text><Text className="mt-2 leading-5 text-muted-foreground">{lesson.summary}</Text></Pressable>)}</View></ScrollView>;
}
