import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { api } from '../../lib/api';
export function LearnScreen({ navigation }: { navigation: { goBack: () => void; navigate: (route: 'WordDetail', params: { id: string }) => void } }) {
  const [index, setIndex] = useState(0); const query = useQuery({ queryKey: ['learn', 'words'], queryFn: () => api.words({}) }); const words = query.data?.items ?? []; const current = words[index];
  if (query.isLoading) return <View className="flex-1 items-center justify-center bg-background"><Text>Çalışma hazırlanıyor…</Text></View>;
  if (query.isError) return <View className="flex-1 items-center justify-center bg-background px-6"><Text className="text-center text-red-700">Çalışma yüklenemedi.</Text></View>;
  if (!current) return <View className="flex-1 items-center justify-center bg-background px-6"><Text className="text-center text-xl font-bold text-foreground">Bugün için kelime yok</Text><Text className="mt-3 text-center text-muted-foreground">Katalogdan kelime seçerek başlayabilirsin.</Text><Pressable onPress={navigation.goBack} className="mt-6 rounded-2xl bg-blue-600 px-6 py-4"><Text className="font-bold text-white">Geri dön</Text></Pressable></View>;
  return <View className="flex-1 bg-background px-6 pt-16"><Text className="text-sm font-bold text-blue-700">KELİME {index + 1} / {words.length}</Text><View className="mt-10 rounded-3xl bg-white p-7"><Text className="text-4xl font-bold text-foreground">{current.term}</Text><Text className="mt-4 text-xl text-muted-foreground">{current.translation}</Text>{current.partOfSpeech ? <Text className="mt-3 text-sm text-blue-700">{current.partOfSpeech}</Text> : null}</View><Pressable onPress={() => index < words.length - 1 ? setIndex(index + 1) : navigation.goBack()} className="mt-8 items-center rounded-2xl bg-blue-600 py-4"><Text className="font-bold text-white">{index < words.length - 1 ? 'Sonraki kelime' : 'Çalışmayı bitir'}</Text></Pressable><Pressable onPress={() => navigation.navigate('WordDetail', { id: current.id })} className="mt-4 items-center"><Text className="text-blue-700">Detayı gör</Text></Pressable></View>;
}
