import { useQuery } from '@tanstack/react-query';
import { useEffect, useState } from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { api } from '../../lib/api';
import { createReviewEventId, enqueueReview, flushReviewQueue } from '../../lib/offline-review-queue';
import { PronunciationButton } from '../../components/PronunciationButton';
export function LearnScreen({ navigation }: { navigation: { goBack: () => void; navigate: (route: 'WordDetail', params: { id: string }) => void } }) {
  const [index, setIndex] = useState(0); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(''); const query = useQuery({ queryKey: ['learn', 'due'], queryFn: () => api.dueWords(20) }); const words = query.data ?? []; const current = words[index];
  useEffect(() => { void flushReviewQueue(item => api.submitReview(item)); }, []);
  if (query.isLoading) return <View className="flex-1 items-center justify-center bg-background"><Text>Çalışma hazırlanıyor…</Text></View>;
  if (query.isError) return <View className="flex-1 items-center justify-center bg-background px-6"><Text className="text-center text-red-700">Çalışma yüklenemedi.</Text></View>;
  if (!current) return <View className="flex-1 items-center justify-center bg-background px-6"><Text className="text-center text-xl font-bold text-foreground">Bugün için kelime yok</Text><Text className="mt-3 text-center text-muted-foreground">Katalogdan kelime seçerek başlayabilirsin.</Text><Pressable onPress={navigation.goBack} className="mt-6 rounded-2xl bg-blue-600 px-6 py-4"><Text className="font-bold text-white">Geri dön</Text></Pressable></View>;
  const review = async (rating: 0 | 1 | 2 | 3) => { setSubmitting(true); setError(''); const item = { wordId: current.id, rating, clientEventId: createReviewEventId() } as const; try { await api.submitReview(item); if (index < words.length - 1) setIndex(index + 1); else navigation.goBack(); } catch (e) { const apiError = e as { status?: number; message?: string }; if (apiError.status === 0) { await enqueueReview(item); setError('Bağlantı yok; değerlendirmen kaydedildi ve bağlantı gelince gönderilecek.'); if (index < words.length - 1) setIndex(index + 1); else navigation.goBack(); } else setError(apiError.message ?? 'Değerlendirme kaydedilemedi.'); } finally { setSubmitting(false); } };
  return <ScrollView className="flex-1 bg-background px-6 pt-16" contentContainerStyle={{ paddingBottom: 56 }}><Text accessibilityRole="header" className="text-sm font-bold text-blue-700">KELİME {index + 1} / {words.length}</Text><View className="mt-10 rounded-3xl bg-white p-7"><Text accessibilityRole="header" className="text-4xl font-bold text-foreground">{current.term}</Text><PronunciationButton text={current.term} /><Text className="mt-4 text-xl text-muted-foreground">{current.translation}</Text>{current.partOfSpeech ? <Text className="mt-3 text-sm text-blue-700">{current.partOfSpeech}</Text> : null}</View><Text accessibilityRole="header" className="mt-8 text-center text-sm font-semibold text-muted-foreground">Ne kadar kolaydı?</Text><View className="mt-3 flex-row gap-2">{([['Tekrar', 0], ['Zor', 1], ['İyi', 2], ['Kolay', 3]] as const).map(([label, rating]) => <Pressable key={label} disabled={submitting} accessibilityRole="button" accessibilityLabel={`${label} olarak değerlendir`} onPress={() => void review(rating)} className="flex-1 items-center rounded-2xl bg-blue-600 py-4"><Text className="font-bold text-white">{label}</Text></Pressable>)}</View>{error ? <Text accessibilityRole="alert" className="mt-4 text-center text-red-700">{error}</Text> : null}<Pressable accessibilityRole="button" accessibilityLabel="Kelime detayını aç" onPress={() => navigation.navigate('WordDetail', { id: current.id })} className="mt-4 items-center"><Text className="text-blue-700">Detayı gör</Text></Pressable></ScrollView>;
}
