import { useState } from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { useQuery } from '@tanstack/react-query';
import { api } from '../../lib/api';
import { PronunciationButton } from '../../components/PronunciationButton';

export function ListeningLabScreen({ navigation }: { navigation: { goBack: () => void } }) {
  const query = useQuery({ queryKey: ['listening-lab'], queryFn: () => api.listeningExercises() });
  const [index, setIndex] = useState(0); const [answer, setAnswer] = useState<string>(); const [revealed, setRevealed] = useState(false); const item = query.data?.[index];
  return <ScrollView className="flex-1 bg-background px-5 pt-14" contentContainerStyle={{ paddingBottom: 56 }}><Pressable accessibilityRole="button" accessibilityLabel="Geri dön" onPress={navigation.goBack}><Text className="font-semibold text-primary">‹ Geri</Text></Pressable><Text accessibilityRole="header" className="mt-8 text-4xl font-bold text-foreground">Dinleme laboratuvarı</Text><Text className="mt-2 text-base leading-6 text-muted-foreground">Dinleme metnini sesli dinle, anlamı seç, sonra cevabını kontrol et.</Text>{query.isError ? <Text accessibilityRole="alert" className="mt-6 rounded-2xl bg-red-50 p-4 text-red-700">Dinleme egzersizleri yüklenemedi. Bağlantını kontrol edip tekrar dene.</Text> : null}{item ? <View className="mt-8 rounded-3xl bg-surface p-6"><View className="flex-row items-center justify-between"><Text className="text-xs font-bold uppercase tracking-widest text-primary">{item.title}</Text><Text className="text-xs font-bold text-muted-foreground">{item.level}</Text></View><Text className="mt-5 text-xl font-bold text-foreground">{item.prompt}</Text><View className="mt-5"><PronunciationButton text={item.transcript} label="Dinleme metnini seslendir" /></View><View className="mt-6 gap-3">{item.options.map(option => <Pressable key={option} accessibilityRole="button" accessibilityLabel={`Cevap: ${option}`} accessibilityState={{ selected: answer === option }} onPress={() => { setAnswer(option); setRevealed(true); }} className={`rounded-2xl border p-4 ${answer === option ? option === item.correctOption ? 'border-emerald-500 bg-emerald-50' : 'border-red-400 bg-red-50' : 'border-transparent bg-background'}`}><Text className="font-semibold text-foreground">{option}</Text></Pressable>)}</View>{revealed ? <View className="mt-5 rounded-2xl bg-primary-soft p-4"><Text className="font-bold text-foreground">{answer === item.correctOption ? 'Doğru!' : `Doğru cevap: ${item.correctOption}`}</Text><Text className="mt-2 text-sm text-muted-foreground">{item.tip}</Text><Text className="mt-4 text-xs font-bold uppercase tracking-widest text-primary">Dinleme metni</Text><Text className="mt-2 text-sm text-foreground">{item.transcript}</Text><Text className="mt-1 text-sm text-muted-foreground">{item.translation}</Text><View className="mt-3"><PronunciationButton text={item.correctOption} label="Doğru cevabı seslendir" /></View></View> : null}<Pressable accessibilityRole="button" accessibilityLabel="Sonraki dinleme egzersizi" disabled={!revealed} onPress={() => { setIndex((index + 1) % (query.data?.length ?? 1)); setAnswer(undefined); setRevealed(false); }} className="mt-6 items-center rounded-2xl bg-primary py-4"><Text className="font-bold text-white">Sonraki egzersiz</Text></Pressable></View> : <Text className="mt-8 text-muted-foreground">Dinleme içerikleri yükleniyor…</Text>}</ScrollView>;
}
