// <auto-generated />
using System;
using EnglishLearning.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnglishLearning.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EnglishLearningDbContext))]
    [Migration("20260926204046_AddQuizEngine")]
    partial class AddQuizEngine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnglishLearning.Domain.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EnglishLearning.Domain.QuizOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "Key")
                        .IsUnique();

                    b.ToTable("quiz_options", (string)null);
                });

            modelBuilder.Entity("EnglishLearning.Domain.QuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Answered")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("VocabularyWordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyWordId");

                    b.HasIndex("SessionId", "Order")
                        .IsUnique();

                    b.ToTable("quiz_questions", (string)null);
                });

            modelBuilder.Entity("EnglishLearning.Domain.QuizSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Level")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("quiz_sessions", (string)null);
                });

            modelBuilder.Entity("EnglishLearning.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAtUtc");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("EnglishLearning.Domain.UserSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentLevel")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("DailyGoal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<string>("LearningPurpose")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("UserId");

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("EnglishLearning.Domain.VocabularyWord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ExampleSentence")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PartOfSpeech")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Pronunciation")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("Term")
                        .IsUnique();

                    b.HasIndex("Level", "Category");

                    b.ToTable("vocabulary_words", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Category = "Daily Life",
                            Definition = "to succeed in doing something",
                            ExampleSentence = "You can achieve your goals.",
                            Level = "A2",
                            PartOfSpeech = "verb",
                            Pronunciation = "/əˈtʃiːv/",
                            Term = "achieve",
                            Translation = "başarmak"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Category = "Personality",
                            Definition = "wanting to know or learn something",
                            ExampleSentence = "Children are naturally curious.",
                            Level = "A2",
                            PartOfSpeech = "adjective",
                            Pronunciation = "/ˈkjʊəriəs/",
                            Term = "curious",
                            Translation = "meraklı"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Category = "Work",
                            Definition = "working well without wasting time or energy",
                            ExampleSentence = "This is an efficient way to study.",
                            Level = "B1",
                            PartOfSpeech = "adjective",
                            Pronunciation = "/ɪˈfɪʃənt/",
                            Term = "efficient",
                            Translation = "verimli"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Category = "Travel",
                            Definition = "an act of travelling from one place to another",
                            ExampleSentence = "The journey took three hours.",
                            Level = "B1",
                            PartOfSpeech = "noun",
                            Pronunciation = "/ˈdʒɜːni/",
                            Term = "journey",
                            Translation = "yolculuk"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Category = "Academic",
                            Definition = "important or noticeable",
                            ExampleSentence = "The study found a significant difference.",
                            Level = "B2",
                            PartOfSpeech = "adjective",
                            Pronunciation = "/sɪɡˈnɪfɪkənt/",
                            Term = "significant",
                            Translation = "önemli"
                        });
                });

            modelBuilder.Entity("EnglishLearning.Domain.QuizOption", b =>
                {
                    b.HasOne("EnglishLearning.Domain.QuizQuestion", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("EnglishLearning.Domain.QuizQuestion", b =>
                {
                    b.HasOne("EnglishLearning.Domain.QuizSession", "Session")
                        .WithMany("Questions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishLearning.Domain.VocabularyWord", "VocabularyWord")
                        .WithMany()
                        .HasForeignKey("VocabularyWordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("VocabularyWord");
                });

            modelBuilder.Entity("EnglishLearning.Domain.QuizSession", b =>
                {
                    b.HasOne("EnglishLearning.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishLearning.Domain.RefreshToken", b =>
                {
                    b.HasOne("EnglishLearning.Domain.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishLearning.Domain.UserSettings", b =>
                {
                    b.HasOne("EnglishLearning.Domain.AppUser", "User")
                        .WithOne("Settings")
                        .HasForeignKey("EnglishLearning.Domain.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishLearning.Domain.AppUser", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("EnglishLearning.Domain.QuizQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("EnglishLearning.Domain.QuizSession", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
